global using Microsoft.AspNetCore.Mvc;
global using System.ComponentModel.DataAnnotations;
global using System.Data.SqlClient;
global using UserLoginFormTest.Data;
global using UserLoginFormTest.Data.Commands;
global using UserLoginFormTest.Data.Queries;
global using UserLoginFormTest.ViewModels;
global using UserLoginFormTest.Services.Encryption;
global using UserLoginFormTest.ProgramExtension;
